version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: US/Eastern
  open-pull-requests-limit: 32
  ignore:
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 1.10.0
    - 1.10.1
    - 1.9.0
    - 2.0.0
    - 2.0.1
    - 2.1.0
    - 2.2.0
    - 2.3.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.3
    - 2.32.4
    - 2.32.8
    - 2.32.9
    - 3.0.3
    - 3.0.4
    - 3.1.1
    - 3.1.2
    - 3.2.1
    - 3.3.1
  - dependency-name: gatsby-plugin-theme-ui
    versions:
    - 0.3.5
    - 0.6.0
    - 0.6.2
    - 0.7.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.11.0
    - 2.11.1
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
    - 3.9.0
    - 4.0.0
    - 4.1.0
    - 4.2.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.10.0
    - 2.11.0
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 3.12.0
    - 3.13.0
    - 4.0.0
    - 4.1.0
    - 4.2.0
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: svelte
    versions:
    - 3.31.2
    - 3.32.1
    - 3.32.3
    - 3.34.0
    - 3.35.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: "@emotion/is-prop-valid"
    versions:
    - 1.0.0
  - dependency-name: styled-components
    versions:
    - 5.2.1
  - dependency-name: sirv-cli
    versions:
    - 1.0.10
